import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { env } from '../lib/env.ts';
import * as authSchema from './schema.ts';
import * as contentSchema from './content-schema.ts';

/**
 * `schema.ts` is generated by the Better Auth CLI and `content-schema.ts` is
 * hand-written; they are merged here so callers see one schema.
 */
const schema = { ...authSchema, ...contentSchema };

const sqlite = new Database(env.DATABASE_PATH);
sqlite.pragma('journal_mode = WAL');
sqlite.pragma('foreign_keys = ON');

export const db = drizzle(sqlite, { schema });
export { schema };
